# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import Message_pb2 as Message__pb2


class CommunicationServiceStub(object):
    """This service is between
    Client: Sending a request of type string "sendcommandflag"
    Server: Sending back a response array "data_array"
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Input = channel.unary_unary(
                '/CommunicationService/Input',
                request_serializer=Message__pb2.Request.SerializeToString,
                response_deserializer=Message__pb2.Response.FromString,
                )


class CommunicationServiceServicer(object):
    """This service is between
    Client: Sending a request of type string "sendcommandflag"
    Server: Sending back a response array "data_array"
    """

    def Input(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CommunicationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Input': grpc.unary_unary_rpc_method_handler(
                    servicer.Input,
                    request_deserializer=Message__pb2.Request.FromString,
                    response_serializer=Message__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CommunicationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CommunicationService(object):
    """This service is between
    Client: Sending a request of type string "sendcommandflag"
    Server: Sending back a response array "data_array"
    """

    @staticmethod
    def Input(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CommunicationService/Input',
            Message__pb2.Request.SerializeToString,
            Message__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
